### ISSUE TITLE
这个如果想和公众号或者小程序对接能给个方法吗

### ISSUE THREAD

**Issue by qdstar** [Jiangtaste/wechat-msg-bridge#1]
使用方法看不懂能具体说说如何和公众号对接嘛

**Comment by Jiangtaste** [comment]
抱歉，我比较懒，写这个主要是用于自己公众号接收用户发送给公众平台的消息。
所以它能做的事仅仅是对用户对公众号发送的消息根据关键词触发一些动作，处理后返回给用户一条消息。
我个人觉得其中只有签名那段源码对你有帮助，其他部分都是对我自己个人项目的特殊需求写的。
公众号相关的参见这里：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421135319
接收详细部分参见这里：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140453
简单说主要是用户发给公众号的消息以及开发者需要的事件推送，小程序同理。
